###############################################################################
# GLOBAL
###############################################################################
[agent]
  interval = "1s"
  flush_interval = "1s"
  flush_jitter = "1s"
  metric_batch_size = 20000
  metric_buffer_limit = 2000000
  hostname = "MSI"


###############################################################################
# WAVEFORM
###############################################################################
[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]
  topics = ["vibration/sensor1/waveform/#"]
  qos = 1
  data_format = "json"
  name_override = "waveform"

###############################################################################
# FFT FREQUENCIES
###############################################################################
[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]
  topics = ["vibration/sensor1/frequencies/#"]
  qos = 1
  data_format = "json"
  name_override = "frequencies"


###############################################################################
# OUTPUTS
###############################################################################

###############################################################################
# WAVEFORM bucket
###############################################################################
[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8086"]
  token = "pwkLGTZgmFEnsjkRiorYybUdmc2RxHh_GO4_IA0FeEzZcwMPj2ykULjsavtbnH3SWgMlNKakr91OzQqC0LMEgg=="
  organization = "UTH"
  bucket = "vibration_waveform"
  timeout = "10s"
  namepass = ["waveform"]

###############################################################################
# FFT bucket
###############################################################################
[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8086"]
  token = "pwkLGTZgmFEnsjkRiorYybUdmc2RxHh_GO4_IA0FeEzZcwMPj2ykULjsavtbnH3SWgMlNKakr91OzQqC0LMEgg=="
  organization = "UTH"
  bucket = "vibration_frequency"
  timeout = "10s"
  namepass = ["frequencies"]