[tool.poetry]
name = "DiplomaThesis"
version = "0.1.0"
description = ""
authors = ["Vasileios Dimitriou"]
license = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
